name: CI/CD Pipeline Local

on:
  push:
    branches: [ "main" ]

jobs:
  # El build se sigue haciendo en la nube (para no gastar tu batería)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build y Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: agusm2002/api-test:latest

      - name: Build y Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: agusm2002/web-test:latest

  # El deploy se hace EN TU DEBIAN (Self-Hosted)
  deploy:
    needs: build-and-push
    runs-on: self-hosted  # <--- ESTO ES LO IMPORTANTE
    steps:
      - name: Pull y Update
        run: |
          cd ~/docker/test_agus
          docker compose pull
          docker compose up -d
          docker image prune -f